all: pagerank123.x pagerank4.x pagerank5.x

pagerank123.x : pagerank123.cpp
	g++ -o pagerank123.x pagerank123.cpp
pagerank4.x : pagerank4.cpp
	g++ -fopenmp -o pagerank4.x pagerank4.cpp
pagerank5.x : pagerank5.cpp
	g++ -fopenmp -o pagerank5.x pagerank5.cpp